### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by sahilvaghela22** [xadhrit/terra#1]
Getting error like this ,

Traceback (most recent call last):
  File "/home/sahil/terra/terra.py", line 357, in <module>
    main()    
  File "/home/sahil/terra/terra.py", line 160, in main
    banner()    
  File "/home/sahil/terra/terra.py", line 136, in banner
    banner = Figlet(font='isometric3',justify='right')
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 794, in __init__
    self.setFont()
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 801, in setFont
    self.Font = FigletFont(font=self.font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 126, in __init__
    self.data = self.preloadFont(font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 147, in preloadFont
    raise FontNotFound(font)
pyfiglet.FontNotFound: isometric3

**Comment by xadhrit** [comment]
try to reinstall pyfiglet.
Can you share what command you are using or screenshot ?
